### ISSUE TITLE
Amélioration possible

### ISSUE THREAD

**Issue by JeremyLaurent** [paul-arthurthiery/Monopoly#3]
1- GIT GUD
2- C mosh go stop l'usine a gaz
3- Documente ton code fagit

**Comment by paul-arthurthiery** [comment]
Je documente pas sinon y'a des fdps ils forkent et ils vont mon code pour le vendre à Alstom qui veut faire du RMI dans ses chiottes. Ptn de moche.

Git on mi level ptn de fragile avec tes 20 lignes de code.

Stop pas savoir faire 0,5 quizup
